"""
orchestrator.py — Multi-Agent Routing and Session Management
============================================================
The orchestrator is the entry point for every clinical chat message.
It decides which specialist agent handles each turn and ensures context
flows correctly across a multi-turn conversation.

Routing logic:
  - Turn 1 is always sent to Triage regardless of content. Before any
    clinical assessment can happen, the system needs to establish who
    the patient is and what brought them in — that is Triage's job.
  - From turn 2 onwards, a lightweight LLM classifier reads the message
    and routes it to whichever of the three agents fits best.

Session state:
  A per-session dictionary tracks the last agent used, the patient ID
  (so downstream agents never ask for it again), and the turn count.
  This is held in memory rather than a database — sessions are
  conversational and short-lived, so the simplicity is justified.

Patient ID propagation:
  Clinical agents need the patient ID to query FHIR. Rather than making
  every agent responsible for extracting it themselves, the orchestrator
  extracts it once when it first appears in any message and injects it
  into subsequent messages as a hidden context prefix. The agent sees a
  complete message and the user never has to repeat themselves.
"""

import os
import re
from typing import Optional
from config import LLM_MODEL, TEMP_ROUTER
from langchain_openai import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage

from triage_agent    import chat          as triage_chat
from specialist_agent import run_specialist
from pharmacy_agent   import run_pharmacy
from dynamic_agent    import run_custom_agent, load_all_agents

# ── Routing LLM ──────────────────────────────────────────────────────────────
# Temperature 0 is critical here — we need a deterministic single-word answer,
# not a creative response. Any temperature above 0 risks "TRIAGE." or "I think
# PHARMACY" which would fall through to the default and misdirect the message.
llm = ChatOpenAI(
    model=LLM_MODEL,
    temperature=TEMP_ROUTER,
    api_key=os.getenv("OPENAI_API_KEY")
)

# ── Router system prompt ──────────────────────────────────────────────────────
# Deliberately terse — the routing call happens on every turn so we keep the
# prompt small to minimise latency and token cost. The agent descriptions are
# written as decision criteria, not capability lists, so the LLM reasons about
# fit rather than just pattern-matching on keywords.
def _build_router_prompt() -> str:
    """
    Build the router system prompt dynamically, including any custom agents
    that have been created by the user. Called on every orchestration turn
    so newly created agents are available immediately without restarting.
    """
    custom_agents = load_all_agents()
    custom_section = ""
    if custom_agents:
        custom_section = "\n" + "\n".join(
            f"- {a['name'].upper().replace(' ', '_')}: {a.get('routing_description', a.get('description', 'Custom clinical agent'))}"
            for a in custom_agents
        )
    return f"""You are a medical routing system. Analyze the user message and decide which agent should handle it.

Agents available:
- TRIAGE: For symptom assessment, urgency evaluation, new complaints, emergency situations, general health questions
- SPECIALIST: For deep condition analysis, referral requests, chronic disease management, diagnostic questions, condition complications
- PHARMACY: For medication questions, drug interactions, prescription queries, allergy-medication conflicts, dosage questions{custom_section}

Respond with ONLY the agent name in uppercase (e.g. TRIAGE, SPECIALIST, PHARMACY{', or the custom agent name' if custom_agents else ''})."""

ROUTER_PROMPT = """You are a medical routing system. Analyze the user message and decide which agent should handle it.

Agents available:
- TRIAGE: For symptom assessment, urgency evaluation, new complaints, emergency situations, general health questions
- SPECIALIST: For deep condition analysis, referral requests, chronic disease management, diagnostic questions, condition complications
- PHARMACY: For medication questions, drug interactions, prescription queries, allergy-medication conflicts, dosage questions

Respond with ONLY one word: TRIAGE, SPECIALIST, or PHARMACY."""

# ── Session state store ───────────────────────────────────────────────────────
# Keyed by session_id (UUID generated by main.py on first turn).
# Each entry holds enough state to make routing decisions and inject context
# without querying FHIR or re-reading the full conversation history.
session_context: dict = {}


# ═══════════════════════════════════════════════════════════════════════════════
#  PATIENT ID EXTRACTION
# ═══════════════════════════════════════════════════════════════════════════════

def extract_patient_id(message: str) -> Optional[str]:
    """
    Pull a patient ID out of a free-text message using regex patterns.

    Users phrase patient IDs in many ways — "my patient ID is pt-001",
    "ID: pt-003", "patient id = demo-001" — so we check several patterns
    rather than requiring a single canonical format. All patterns are
    anchored to common lead-in phrases to avoid false positives on other
    numeric strings in the message (phone numbers, dates, etc.).

    Returns None rather than raising so callers can treat a missing ID
    as a recoverable situation rather than an error.
    """
    patterns = [
        r'patient\s+id\s+is\s+([\w-]+)',
        r'patient\s+id:\s*([\w-]+)',
        r'my\s+id\s+is\s+([\w-]+)',
        r'id\s+is\s+([\w-]+)',
        r'\bid\s*[:=]\s*([\w-]+)',
    ]
    for pattern in patterns:
        match = re.search(pattern, message.lower())
        if match:
            return match.group(1)
    return None


# ═══════════════════════════════════════════════════════════════════════════════
#  LLM-BASED MESSAGE ROUTER
# ═══════════════════════════════════════════════════════════════════════════════

def route_message(message: str) -> str:
    """
    Classify a message and return the name of the agent that should handle it.

    Uses a separate LLM call rather than keyword matching because clinical
    language is ambiguous — "can I take this with my heart medication?" is a
    Pharmacy question, but "my heart medication isn't working" is Specialist.
    A rule-based approach would need an ever-growing list of exceptions;
    the LLM generalises naturally.

    Falls back to TRIAGE on any unexpected output — Triage is the safest
    default because it will either handle the query itself or ask a
    clarifying question that surfaces enough information to route correctly
    on the next turn.
    """
    response = llm.invoke([
        SystemMessage(content=_build_router_prompt()),
        HumanMessage(content=message)
    ])
    route = response.content.strip().upper().replace(' ', '_')

    # Accept built-in agent names or any registered custom agent name
    built_in = {"TRIAGE", "SPECIALIST", "PHARMACY"}
    custom_names = {
        a["name"].upper().replace(" ", "_")
        for a in load_all_agents()
    }
    valid_routes = built_in | custom_names

    if route not in valid_routes:
        print(f"Orchestrator: unexpected route '{route}', defaulting to TRIAGE")
        route = "TRIAGE"

    return route


# ═══════════════════════════════════════════════════════════════════════════════
#  PATIENT CONTEXT INJECTION
# ═══════════════════════════════════════════════════════════════════════════════

def inject_patient_context(message: str, patient_id: str) -> str:
    """
    Prepend a hidden context block to the message carrying the patient ID.

    Without this, an agent receiving "what medications should I adjust?"
    on turn 4 has no idea which patient is being discussed — it would ask
    for the ID again, frustrating the user and breaking conversation flow.

    The context block is formatted as a bracketed instruction so the agent's
    system prompt can teach it to treat bracketed prefixes as dispatcher
    context rather than patient speech. The ID is only injected if it isn't
    already present in the message to avoid redundant repetition.
    """
    if patient_id and patient_id.lower() not in message.lower():
        return (
            f"[Context: Patient ID is {patient_id}. "
            f"Do NOT ask for patient ID again.] {message}"
        )
    return message


# ═══════════════════════════════════════════════════════════════════════════════
#  MAIN ORCHESTRATION FUNCTION
# ═══════════════════════════════════════════════════════════════════════════════

def orchestrate(session_id: str, message: str) -> dict:
    """
    Process one turn of a clinical conversation and return the agent's response.

    Called by main.py for every /chat request and by the vitals system
    when an automated critical alert needs an AI assessment.

    Flow per turn:
      1. Initialise session state if this is the first message.
      2. Extract and store any patient ID mentioned in the message.
      3. Decide which agent handles this turn (Triage for turn 1, LLM
         routing thereafter).
      4. Inject the stored patient ID into the message if the receiving
         agent needs it and it isn't already there.
      5. Dispatch to the chosen agent and return the structured response.

    Returns a dict rather than a plain string so main.py can report which
    agent was used back to the frontend — the sidebar agent network panel
    uses this to highlight the active agent and increment its call counter.
    """
    # ── Session initialisation ────────────────────────────────────────────────
    if session_id not in session_context:
        session_context[session_id] = {
            "last_agent": None,
            "patient_id": None,
            "turn_count": 0
        }

    ctx = session_context[session_id]
    ctx["turn_count"] += 1

    # ── Patient ID tracking ───────────────────────────────────────────────────
    # Store the ID as soon as it appears so all subsequent turns have it,
    # regardless of which agent handled the turn where it was first mentioned.
    extracted_id = extract_patient_id(message)
    if extracted_id:
        ctx["patient_id"] = extracted_id

    # ── Agent selection ───────────────────────────────────────────────────────
    # Turn 1 always goes to Triage — it's the intake agent responsible for
    # collecting the chief complaint before specialist agents get involved.
    if ctx["turn_count"] == 1:
        agent = "TRIAGE"
    else:
        agent = route_message(message)

    ctx["last_agent"] = agent

    # ── Context enrichment ────────────────────────────────────────────────────
    # Specialist and Pharmacy always get the patient ID — they query FHIR
    # immediately and will fail silently without it. Triage gets it from
    # turn 3 onwards (by turn 2 it should already have introduced itself
    # and collected the presenting complaint).
    enriched_message = message
    if ctx["patient_id"]:
        if agent in ["SPECIALIST", "PHARMACY"]:
            enriched_message = inject_patient_context(message, ctx["patient_id"])
        elif agent == "TRIAGE" and ctx["turn_count"] > 2:
            enriched_message = inject_patient_context(message, ctx["patient_id"])
        else:
            # Custom agents always get the patient ID — they need it to
            # fetch FHIR data since they don't share memory with built-in agents
            built_in = {"TRIAGE", "SPECIALIST", "PHARMACY"}
            if agent not in built_in:
                enriched_message = inject_patient_context(message, ctx["patient_id"])

    # ── Agent dispatch ────────────────────────────────────────────────────────
    print(f"Orchestrator: session={session_id[:8]} turn={ctx['turn_count']} → {agent}")

    if agent == "TRIAGE":
        response = triage_chat(session_id, enriched_message)
    elif agent == "SPECIALIST":
        response = run_specialist(session_id, enriched_message)
    elif agent == "PHARMACY":
        response = run_pharmacy(session_id, enriched_message)
    else:
        # Custom agent — find by normalised name
        custom_agents = load_all_agents()
        matched = next(
            (a for a in custom_agents
             if a["name"].upper().replace(" ", "_") == agent),
            None
        )
        if matched:
            response = run_custom_agent(matched["id"], session_id, enriched_message)
        else:
            # Agent was deleted between routing and dispatch — fallback
            print(f"Orchestrator: custom agent '{agent}' not found, falling back to TRIAGE")
            response = triage_chat(session_id, enriched_message)
            agent = "TRIAGE"

    return {
        "response":   response,
        "agent_used": agent,
        "session_id": session_id,
        "turn":       ctx["turn_count"]
    }